### ISSUE TITLE
432p 혹시나 어려움 겪으실까봐 알려드립니다.

### ISSUE THREAD

**Issue by ongbune** [smarthug/UE4-CPP-Book#3]
먼저 여기까지 오시지 않았다면 여기까지 오신 후에 이 글을 읽어보시길 추천드립니다.

PossessedBy()를 보면 플레이어 컨트롤러가 빙의를 했는지 AI컨트롤러가 빙의했는지에 따라 로직이 갈리는데 왜 플레이어 컨트롤러가 빙의하면 SetControlMode(EControlMode::Diablo)를 했는지 궁금하실 수도 있습니다.

저 같은 경우에는 컨트롤 모드는 구현안해서 그 줄을 지웠었는데 제 캐릭터가 이상하게 돌아버리는 문제가 생겼었는데요, 단도직입적으로 말씀드리면 AI 컨트롤러는 플레이어 컨트롤러가 빙의하기전 빙의됩니다. 즉, 캐릭터가 2개가 있으면 먼저 AI 컨트롤러는 그 2개의 캐릭터에 빙의하고 플레이어 컨트롤러가 그 2개중 하나를 빙의하기 때문에 문제가 생겼었습니다.

이해가 되실련지 잘 모르겠는데... 저처럼 SetControlMode(EControlMode::Diablo)를 지워보시면 이해가 가리라 생각합니다.
책에는 이런 내용이 없어요... 진짜 진심 너무 불친절한 책

**Comment by smarthug** [comment]
의견 주셔서 감사합니다.

저는  SetControlMode(EControlMode::Diablo) 를 지워보니 공격은 가능한데 움직이진 않더군요 ;;
possessedBy 를 override 하기전에는 작동하는걸로 보아  possessedBy 를 override 하면은 AI 컨트롤러가 빙의되면서  바뀐  컨트롤 설정을 재설정 해야하는것으로 보여집니다.
 ABCharacter 생성자 -> AI Controller -> PossessedBy  순서로  진행되는것 같습니다.
그래서  생성자에서 이미 호출한   SetControlMode(EControlMode::Diablo) 를 PossessedBy 에서 또 호출할 필요가 있는거구요.

의견 참고해서 글에 올려놓겠습니다

**Comment by smarthug** [comment]
- 504p , 현재 설정상 플레이어도 전용 AI 컨트롤러가 자동으로 부착되므로 PossessedBy 함수가 두 번 호출됩니다.

player 건 AI 건  둘 다 SetControlMode(EControlMode::NPC);  가 실행되네요. 플레이어인데 SetControlMode(EControlMode::NPC);  가 적용되어 있어  SetControlMode(EControlMode::Diablo) 를 다시 적용해주는 거였네요 ;;
